export interface WeatherData {
  current: {
    temperature: number | null,
    relativeHumidity: number | null,
    apparentTemperature: number | null
    isDay: number | null,
    windSpeed: number | null,
    windDirection: number | null,
    windGusts: number | null,
    precipitation: string | null,
    rain: string | null,
    showers: string | null,
    weatherCode: number | null,
    surfacePressure: number | null,
    snowfall: number | null,
    cloudCover: number | null,
    time: Date | null,
  },
  hourly: {
    temperature: number[] | null,
    humidity: number[] | null,
    windSpeed: number[] | null,
    windDirection: number[] | null,
    windGusts: number[] | null,
    surfacePressure: number[] | null,
    precipitationProbability: number[] | null,
    weatherCode: number[] | null,
    time: Date[] | null,
  },
  daily : {
    temperatureMax: number[] | null,
    temperatureMin: number[] | null,
    weatherCode: number[] | null,
    sunrise: Date[] | null,
    sunset: Date[] | null,
    windSpeedMax: number[] | null,
    windGustsMax: number[] | null,
    windDirectionDom: number[] | null,
    precipitationProbabilityMax: number[] | null,
    daylightDuration: number[] | null,
    time: Date[] | null,
  },
};